apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- svc.yaml
configMapGenerator:
- envs:
  - env
  name: substrate-rpc-proxy-config
images:
- name: substrate-rpc-proxy
  newName: test
